### ISSUE TITLE
AttributeError: _parse_flags

### ISSUE THREAD

**Issue by zhiqiangdon** [HazyResearch/tanda#10]
Hi,

I am trying to run your code on tensorflow 1.2 and 1.4. They show the same error:

Traceback (most recent call last):
  File "experiments/mnist/train.py", line 50, in <module>
    n_classes=10)
  File "/home/don/projects/tanda/experiments/train_scripts.py", line 191, in train
    X_train, dims, tfs, log_path, **kwargs
  File "/home/don/projects/tanda/experiments/train_scripts.py", line 350, in train_tan
    log_dict = create_run_log(LOGDIR, FLAGS)
  File "/home/don/projects/tanda/experiments/utils.py", line 55, in create_run_log
    flags._parse_flags()
  File "/home/don/tensorflow1.2/local/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 85, in __getattr__
    return wrapped.__getattr__(name)
  File "/home/don/tensorflow1.2/local/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 470, in __getattr__
    raise AttributeError(name)
AttributeError: _parse_flags

It seems that class tf.flags doesn't have function "_parse_flags". Any hint to solve this?

Thanks,
Zhiqiang

**Comment by paperfactory** [comment]
The same error with me.

**Comment by zhys513** [comment]
The same error with me.

**Comment by zhys513** [comment]
The same error with me.
My development environment is tensorflow1.5.0 GPU  centos7  python3.5.2

**Comment by zhys513** [comment]
hi，
I download the branch and try again，show this error，Please inform you of the development environment. Thank you
 File "experiments/mnist/train.py", line 50, in <module>
    n_classes=10)
  File "/home/yszheng/tanda/experiments/train_scripts.py", line 191, in train
    X_train, dims, tfs, log_path, **kwargs
  File "/home/yszheng/tanda/experiments/train_scripts.py", line 350, in train_tan
    log_dict = create_run_log(LOGDIR, FLAGS)
  File "/home/yszheng/tanda/experiments/utils.py", line 55, in create_run_log
    log_dict.update(flags.FLAGS)
  File "/home/yszheng/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/flags.py", line 85, in __getattr__
    return wrapped.__getattr__(name)
  File "/home/yszheng/anaconda3/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 470, in __getattr__
    raise AttributeError(name)
AttributeError: FLAGS

**Comment by henryre** [comment]
Hi all, apologies for the slow response here, but this is now fixed on master

**Comment by dixiematt8** [comment]
What is the fix for it

**Comment by caterpillars** [comment]
I got the same error. (I am using tensorflow1.15.0rc1 since I can't find tensorflow 1.2). Could you please let me know how to fix this issue?

Thanks

**Comment by caterpillars** [comment]
I changed experiments/util.py based on this [link](https://github.com/HazyResearch/tanda/commit/4e04d26ad5863092b45d143e8765a2fb88b920d0) . Now I got this error:

Traceback (most recent call last):
  File "experiments/mnist/train.py", line 50, in <module>
    n_classes=10)
  File "/Users/hongli/Work/tanda/experiments/train_scripts.py", line 192, in train
    X_train, dims, tfs, log_path, **kwargs
  File "/Users/hongli/Work/tanda/experiments/train_scripts.py", line 351, in train_tan
    log_dict = create_run_log(LOGDIR, FLAGS)
  File "/Users/hongli/Work/tanda/experiments/utils.py", line 58, in create_run_log
    log_dict.update(flags.FLAGS)
  File "/Users/hongli/Work/env_tanda/lib/python3.7/site-packages/tensorflow_core/python/platform/flags.py", line 85, in __getattr__
    return wrapped.__getattr__(name)
  File "/Users/hongli/Work/env_tanda/lib/python3.7/site-packages/absl/flags/_flagvalues.py", line 473, in __getattr__
    raise AttributeError(name)
AttributeError: FLAGS

**Comment by caterpillars** [comment]
I get it to work by directly assign  flags.flag_values_dict() to log_dict.

**Comment by caterpillars** [comment]
I was able to get around it by 

log_dict.update(flags.flag_values_dict())
